trainer:
  max_epochs: 100
  accelerator: auto
  callbacks:
  - class_path: lightning.pytorch.callbacks.ModelCheckpoint
    init_args:
      dirpath: checkpoints/wisconsin_breast_cancer_classifier/
      filename: "best"
      monitor: val/loss
      mode: min
      save_top_k: 1
      save_last: false
      auto_insert_metric_name: false
      every_n_epochs: 1
      save_on_train_epoch_end: true
  - class_path: lightning.pytorch.callbacks.LearningRateMonitor
    init_args:
      logging_interval: epoch
  logger:
    class_path: lightning.pytorch.loggers.CSVLogger
    init_args:
      save_dir: lightning_logs
      name: wisconsin_breast_cancer_classifier

model:
  class_path: training.lit_classifier.LitClassifier
  init_args:
    model:
      class_path: models.classifiers.TabularClassifier
      init_args:
        input_types:
          - numerical
          - numerical
          - numerical
          - numerical
          - numerical
          - numerical
          - numerical
          - numerical
          - numerical
          - numerical
          - numerical
          - numerical
          - numerical
          - numerical
          - numerical
          - numerical
          - numerical
          - numerical
          - numerical
          - numerical
          - numerical
          - numerical
          - numerical
          - numerical
          - numerical
          - numerical
          - numerical
          - numerical
          - numerical
          - numerical
        cardinalities: []
        hidden_dims: [64, 32]
        num_classes: 2
        dropout: 0.2

    initial_lr: 5e-3
    final_lr: 1e-6
    weight_decay: 1e-4

data:
  class_path: training.datamodules.wisconsin_breast_cancer.WisconsinBreastCancerDataModule
  init_args:
    filepath: data/WisconsinBreastCancer/raw.parquet
    batch_size: 128
    val_fraction: 0.1
    test_fraction: 0.1
    seed: 42
    num_workers: 4
